### ISSUE TITLE
Villager Upside down problem (test not actual bug)

### ISSUE THREAD

**Issue by WinstonLuo07** [ArvickC/CakeCraft-RPG#19]
**Describe the bug**

Villager turning upside down when right-clicked LOL

**To Reproduce**
1. Right click on villager (any kind)
**Expected behavior**
trade menu, not upside down
**Screenshots**
none
**Plugin Version**
Type "/ver <PluginName>" to see the version of the plugin, paste it here
1.0.0
**Additional context**
none

**Comment by ArvickC** [comment]
You are just being stoopid!
